name: CI
on: push
env:
  CARGO_TERM_COLOR: always
jobs:

  ci:
    needs: [build, test, docs, coverage]
    name: CI
    runs-on: 'ubuntu-latest'
    steps:
      - name: Done
        run: exit 0

  build:
    name: Build
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose

  test:
    name: Test
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Test Standard
        run: cargo test --verbose
      - name: Test Serde
        run: cargo test --verbose -F serde

  docs:
    name: Docs
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - run: cargo doc --verbose

  coverage:
    name: Coverage
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3
    - name: Install LLVM-Coverage
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Measure Coverage
      run: cargo llvm-cov --lcov --output-path coverage.lcov
    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.lcov
